export const container: string;
export const editMode: string;
export const formula: string;
export const editorContainer: string;
export const input: string;
export const invalid: string;
export const buttonsContainer: string;
export const buttonAction: string;
export const inactive: string;
